name: Manual SonarQube Analysis for Pre-Built Project - Automatic Analysis Disabled

on: 
  workflow_dispatch:

jobs:
  analyze_with_sonarqube:
    name: Analyze with SonarQube
    runs-on: ubuntu-latest

    env:
      WORKFLOW_SONAR_PROJECT_KEY: "diego4bits_quality-actions" 
      WORKFLOW_SONAR_PROJECT_NAME: "quality-actions"         
      WORKFLOW_SONAR_PROJECT_VERSION: "1.0.0-SNAPSHOT"    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # fetch-depth: 0 es crucial para que SonarQube pueda analizar correctamente
          # el código nuevo, especialmente en Pull Requests (aunque con workflow_dispatch es menos crítico para PRs).
          fetch-depth: 0

      - name: Set up JDK 11 (for SonarScanner)
        uses: actions/setup-java@v4
        with:
          # El SonarScanner CLI requiere Java para ejecutarse.
          # Usamos Java 11 basado en la configuración de tu proyecto.
          java-version: '17'
          distribution: 'temurin'

      - name: Create sonar-project.properties
        run: |
          echo "sonar.projectKey=${{ env.WORKFLOW_SONAR_PROJECT_KEY }}" > sonar-project.properties
          echo "sonar.projectName=${{ env.WORKFLOW_SONAR_PROJECT_NAME }}" >> sonar-project.properties
          echo "sonar.projectVersion=${{ env.WORKFLOW_SONAR_PROJECT_VERSION }}" >> sonar-project.properties
          echo "sonar.organization=diego4bits" >> sonar-project.properties
          

          echo "sonar.sources=main/java" >> sonar-project.properties # Tus fuentes están en main/java
          echo "sonar.tests=test/java" >> sonar-project.properties     # Tus tests están en test/java
          

          echo "sonar.java.binaries=target/" >> sonar-project.properties
          

          echo "sonar.sourceEncoding=UTF-8" >> sonar-project.properties


      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }} 
