name: Dependency-Check – Test run

on:
  workflow_dispatch:
  push:   # run it manually from the Actions tab

permissions: 
  write-all
  read-all
jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ─────────────── Run the custom Action ───────────────
      - name: OWASP Dependency-Check
        id: depcheck
        uses: ./.github/actions/dependency-check      # if the Action lives in this repo;
                              # otherwise use   owner/repo@vX
        with:
          scan-args: |
            --disableRetireJS
            --scan "**/*.java"
            --format HTML

      # ─────────────── Show the report content ─────────────
      - name: List report files
        run: |
          echo "Report directory: /github/workspace"
          ls -R /github/workspace


